# .bashrc

if [ -x ~/.bashrc_private ]; then
  # 一些敏感的环境变量存放在~/.bashrc_private脚本里
	source ~/.bashrc_private
fi

PS1='\n\[\e[32;1m\]\u@\H \[\e[33;1m\]\w\[\e[0m\]\n\$ '
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
