source $VIMRUNTIME/vimrc_example.vim


""" 防止重复执行 
let g:IncludeAllFile = $HOME."/.vim/vimrc.d/include_all.xvim"
if filereadable(g:IncludeAllFile) 
  exec "source ". g:IncludeAllFile
endif



""" 外观
set go=e
" 部分终端会变成灰色  
" colo evening 
" 设置gvim鼠标直接选择复制
" set mouse=a
set mouse=

" 文件选项
set fileencodings=utf-8,ucs-bom,cp936,GBK
set fileformat=unix
set encoding=utf-8

set nu
set shiftround
set nocompatible
" set noautoindent
set ai

set autochdir
set ignorecase smartcase
set nowrapscan
set tabstop=4
set shiftwidth=4
set expandtab
" set linebreak

""" config backup
" set nobackup
silent !mkdir -p /tmp/vim`id -u` > /dev/null 2>&1
let g:tmpdir="/tmp/vim".ChompedSystem("id -u")
let &g:undodir=g:tmpdir
let &g:backupdir=g:tmpdir
let &g:directory=g:tmpdir

""" 总显示状态栏
set laststatus=2
" 显示当前文件路径
" set statusline=[%n]\ %f%m%r%h\ \|\ \ pwd:\ %{CurDir()}\ \ \|%=\|\ %l,%c\ %p%%\ %{((&fenc==\"\")?\"\":\"\ \|\ \".&fenc)} 
" set statusline=%{CurDir()}\/%f

""" 窗口切换
nmap <C-up>    <C-W><C-K>
nmap <C-Down>  <C-W><C-J>
nmap <C-Left>  <C-W><C-H>
nmap <C-Right> <C-W><C-L>


""" for Taglist
"设定系统中ctags程序的位置
let Tlist_Ctags_Cmd = "ctags"
"有多个文件的tag时，只显示当前文件的
let Tlist_Show_One_File = 1 
"如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Exit_OnlyWindow = 1 
" let Tlist_Use_Right_Window = 1 "在右侧窗口中显示taglist窗口
" let Tlist_Use_Left_Window = 1 

""" for vim-matlab
let g:matlab_server_launcher = 'vim'
let g:matlab_server_split = 'vertical'


" 自动打开Tlist
autocmd VimEnter *.cpp,*.h,*.hpp,*.c,*.cc,*.mq4,*.s,*.go :Tlist
autocmd VimEnter *.cpp,*.h,*.hpp,*.c,*.cc,*.mq4,*.go :set foldmethod=indent
autocmd FileType python setlocal omnifunc=pysmell#Complete

""" vim 退出后保留屏幕内容
" set t_ti=
" set t_te=

syntax on
